// Generated by the lead from ApiMetadata.generated.inc: one call per overload of APIs
// described in runtime/ApiSemantics.cpp (makeBowlWC .. makeBowlShower).
FdPoint3d a288_0 = FdPoint3d(5, 1, 3);
FdVector3d a288_1 = FdVector3d(1, 0, 0);
FdVector3d a288_2 = FdVector3d(0, 0, 1);
makeBowlWC(a288_0, a288_1, a288_2, 40.5, 45.5, 50.5, 2, 2);
FdPoint3d a289_0 = FdPoint3d(5, 1, 3);
FdVector3d a289_1 = FdVector3d(1, 0, 0);
FdVector3d a289_2 = FdVector3d(0, 0, 1);
makeBowlSink(a289_0, a289_1, a289_2, 40.5, 45.5, 50.5, 2, 2);
FdPoint3d a290_0 = FdPoint3d(5, 1, 3);
FdVector3d a290_1 = FdVector3d(1, 0, 0);
FdVector3d a290_2 = FdVector3d(0, 0, 1);
makeBowlBath(a290_0, a290_1, a290_2, 40.5, 45.5, 50.5, 2, 2);
FdPoint3d a291_0 = FdPoint3d(5, 1, 3);
FdVector3d a291_1 = FdVector3d(1, 0, 0);
FdVector3d a291_2 = FdVector3d(0, 0, 1);
makeBowlShower(a291_0, a291_1, a291_2, 40.5, 45.5, 50.5, 2, 2);
