// Generated by the lead from ApiMetadata.generated.inc: one call per overload of APIs
// described in runtime/ApiSemantics.cpp (makeVerySimpleTube .. makeFacettedCylinder).
FdPoint3d a242_0 = FdPoint3d(5, 1, 3);
FdPoint3d a242_1 = FdPoint3d(15, 3, 4);
makeVerySimpleTube(a242_0, a242_1, 40.5, 2);
FdPoint3d a243_0 = FdPoint3d(5, 1, 3);
FdVector3d a243_1 = FdVector3d(1, 0, 0);
makeFlatRing(a243_0, a243_1, 40.5, 45.5, 2);
FdPoint3d a244_0 = FdPoint3d(5, 1, 3);
FdVector3d a244_1 = FdVector3d(1, 0, 0);
makeFlatDisc(a244_0, a244_1, 40.5, 2);
FdPoint3d a245_0 = FdPoint3d(5, 1, 3);
FdVector3d a245_1 = FdVector3d(1, 0, 0);
makeDisc(a245_0, a245_1, 40.5, 45.5, 2, true);
FdPoint3d a246_0[2] = {FdPoint3d(5, 1, 3), FdPoint3d(15, 3, 4)};
makeSimpleTube(a246_0, 40.5, 45.5, 2);
FdPoint3d a247_0[2] = {FdPoint3d(5, 1, 3), FdPoint3d(15, 3, 4)};
makeVerySimpleTube(a247_0, 40.5, 2);
FdPoint3d a248_1[5] = {FdPoint3d(5, 1, 3), FdPoint3d(15, 3, 4), FdPoint3d(25, 5, 5), FdPoint3d(35, 7, 6), FdPoint3d(45, 9, 7)};
FdVector3d a248_2[5] = {FdVector3d(1, 0, 0), FdVector3d(0, 0, 1), FdVector3d(0, 1, 0), FdVector3d(0, -1, 0), FdVector3d(1, 1, 0)};
FdVector3d a248_3[5] = {FdVector3d(1, 0, 0), FdVector3d(0, 0, 1), FdVector3d(0, 1, 0), FdVector3d(0, -1, 0), FdVector3d(1, 1, 0)};
double a248_4[5] = {40.5, 45.5, 50.5, 55.5, 60.5};
double a248_5[5] = {40.5, 45.5, 50.5, 55.5, 60.5};
bool a248_6[5] = {true, false, true, true, false};
makeBoxFromPlanes(2, a248_1, a248_2, a248_3, a248_4, a248_5, a248_6, true, false, 5, 6, 60.5);
FdPoint3d a250_0 = FdPoint3d(5, 1, 3);
FdPoint3d a250_1 = FdPoint3d(15, 3, 4);
FdVector3d a250_2 = FdVector3d(1, 0, 0);
makeFacettedCylinder(a250_0, a250_1, a250_2, 40.5, 45.5, 50.5, 55.5, false, true);
