// Generated by the lead from ApiMetadata.generated.inc: one call per overload of APIs
// described in runtime/ApiSemantics.cpp (addCenterPolyLine .. addEraseLine).
FdPoint3d a138_0[5] = {FdPoint3d(5, 1, 3), FdPoint3d(15, 3, 4), FdPoint3d(25, 5, 5), FdPoint3d(35, 7, 6), FdPoint3d(45, 9, 7)};
addCenterPolyLine(a138_0, 2);
FdPoint3d a139_0 = FdPoint3d(5, 1, 3);
FdVector3d a139_1 = FdVector3d(1, 0, 0);
FdVector3d a139_2 = FdVector3d(0, 0, 1);
addCenterArc(a139_0, a139_1, a139_2, 40.5, 45.5, 50.5);
FdPoint3d a140_0 = FdPoint3d(5, 1, 3);
addCircularConnector(a140_0);
FdPoint3d a141_0 = FdPoint3d(5, 1, 3);
FdVector3d a141_1 = FdVector3d(1, 0, 0);
addCircularConnector(a141_0, a141_1);
FdPoint3d a142_0 = FdPoint3d(5, 1, 3);
addCircularConnector(a142_0, 40.5);
FdPoint3d a143_0 = FdPoint3d(5, 1, 3);
FdVector3d a143_1 = FdVector3d(1, 0, 0);
addCircularConnector(a143_0, a143_1, 40.5);
FdPoint3d a144_0 = FdPoint3d(5, 1, 3);
FdVector3d a144_1 = FdVector3d(1, 0, 0);
FdVector3d a144_2 = FdVector3d(0, 0, 1);
addRectangularConnector(a144_0, a144_1, a144_2, 40.5, 45.5);
FdPoint3d a145_0 = FdPoint3d(5, 1, 3);
FdPoint3d a145_1 = FdPoint3d(15, 3, 4);
addEraseLine(a145_0, a145_1);
