// Generated by the lead from ApiMetadata.generated.inc: one call per overload of APIs
// described in runtime/ApiSemantics.cpp (makeInfinite .. makeDonutSection2).
FdPoint3d a181_0 = FdPoint3d(5, 1, 3);
FdVector3d a181_1 = FdVector3d(1, 0, 0);
FdVector3d a181_2 = FdVector3d(0, 0, 1);
makeInfinite(a181_0, a181_1, a181_2, 40.5, 45.5);
FdPoint3d a182_0 = FdPoint3d(5, 1, 3);
FdVector3d a182_1 = FdVector3d(1, 0, 0);
FdVector3d a182_2 = FdVector3d(0, 0, 1);
makeReversedSigma(a182_0, a182_1, a182_2, 40.5, 45.5);
FdPoint3d a183_0[5] = {FdPoint3d(5, 1, 3), FdPoint3d(15, 3, 4), FdPoint3d(25, 5, 5), FdPoint3d(35, 7, 6), FdPoint3d(45, 9, 7)};
makePolygonalHatch(a183_0, 2);
FdPoint3d a184_0 = FdPoint3d(5, 1, 3);
FdVector3d a184_1 = FdVector3d(1, 0, 0);
FdVector3d a184_2 = FdVector3d(0, 0, 1);
makeBowTieHatch(a184_0, a184_1, a184_2, 40.5, 45.5);
FdPoint3d a185_0 = FdPoint3d(5, 1, 3);
FdVector3d a185_1 = FdVector3d(1, 0, 0);
FdVector3d a185_2 = FdVector3d(0, 0, 1);
makeRectHatch(a185_0, a185_1, a185_2, 40.5, 45.5);
FdPoint3d a187_0 = FdPoint3d(5, 1, 3);
FdVector3d a187_1 = FdVector3d(1, 0, 0);
makeRectSimpleGrill(a187_0, a187_1, 40.5, 45.5, true);
FdPoint3d a188_0 = FdPoint3d(5, 1, 3);
FdVector3d a188_1 = FdVector3d(1, 0, 0);
makeCircSimpleGrill(a188_0, a188_1, 40.5, 45.5, true);
FdPoint3d a189_0 = FdPoint3d(5, 1, 3);
FdVector3d a189_1 = FdVector3d(1, 0, 0);
makeDonutSection2(a189_0, a189_1, 40.5, 45.5, 50.5, 55.5, 60.5, 65.5);
