export {
  connectorGeometryChanged,
  connectorStatusText,
  connectorTypeIndex,
  copyDefinition,
  kAngleLabels,
  kAxisLabels,
  kConnectorTypes,
  kLinkTableHeaders,
  kOrientationLabels,
  kSizePlaceholder,
  linkParameterNames,
  linkTableTexts,
  orientationIndex,
  pointNameError,
  uniquePointName,
} from '@/entities/connector/lib/link';
